### ISSUE TITLE
Tasklist do desenvolvimento

### ISSUE THREAD

**Issue by PedroDelaRisso** [PedroDelaRisso/Profile.gg#1]
### **PRIMEIRAMENTE**
- A aparência do projeto vem por último.
--------
# Tasks
- [x] Requisições na Riot API.
  - [x] Descobrir como fazer, fazer e testar.
- [ ] Escrever na tela os dados advindos das requisições.
  - [ ] Definir quais informações selecionar nos dados das partidas.
